### ISSUE TITLE
Improvement: melhorar a função delete de grupo e de links

### ISSUE THREAD

**Issue by paulobarbos00** [cerberus-project/cerberus-front#49]
- [x] Melhorar retornos de erro nos services e controllers.
- [x] Deploy

**Comment by vikmiranda** [comment]
* Delete Group: 
O services pode retornar duas mensagens possiveis de erro, é preciso deixar esse retorno légivel no controller para retornar o status HTTP correspondente, para usuario não autorizado e grupo não encontrado.
