### ISSUE TITLE
Improvement: Criar Use Case para as histórias.

### ISSUE THREAD

**Issue by YtaloGabriel** [cerberus-project/cerberus-front#6]
- [x] Criar pasta e alocar Use Case das HU.
- [x] Linkar os UC na descrição de cada Card respectivo.

**Comment by paulobarbos00** [comment]
- [ ] Criar pasta e alocar _Use Case_ das HU.
- [ ] Linkar os UC na descrição de cada Card respectivo.

**Comment by paulobarbos00** [comment]
Local do repositório: cerberus-front/documentation/use-case/

[https://github.com/cerberus-project/cerberus-front/tree/main/documentation/use-case](url)

**Comment by gomeshud** [comment]
REVIEW:

*Precisa melhorar documentação:
- [ ]  diferenciar fluxo alternativo de fluxo de exceção.
- [ ] consertar link;
- [ ] consertar extensão dos arquivos (.md).
